# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the merchant1 branch
  push:
    branches: [ merchant1 ]
  pull_request:
    branches: [ merchant1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v2
        with:
          xcode-version: latest-stable
          
      - name: Setup ruby
        uses: ruby/setup-ruby@v2
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          
      - name: Install Pods
        run: |
         pod install
         
      - name: run tests
        run: | 
          bundle exec fastlane tests
         

